# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.22.0
    hooks:
    -   id: pyupgrade
        args: ["--py313-plus", "--keep-runtime-typing"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/pycqa/pylint
    rev: v4.0.5
    hooks:
    -   id: pylint
        args: [--extension-pkg-whitelist=confluent_kafka, --load-plugins=pylint.extensions.bad_builtin, --load-plugins=pylint.extensions.mccabe]
        additional_dependencies: ["click", "confluent_kafka", "cotyledon", "pytest", "pytest_mock"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        files: ^eventbusk/
        additional_dependencies: ["types-click"]

-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: .venv/bin/pytest
        language: script
        pass_filenames: false
        always_run: true
